// Auto-generated by OpenLane
module soc_top(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  inout vccd1,
  inout vssd1,
  input clk,
  input rst,
  input prog_we,
  input[7:0] prog_addr,
  input[31:0] prog_data,
  output[31:0] dbg_imem_addr,
  output[31:0] dbg_imem_data,
  output[31:0] dbg_dmem_addr,
  output[31:0] dbg_dmem_wdata,
  output[31:0] dbg_dmem_rdata,
  output dbg_dmem_we
);
endmodule
